include: package:flutter_lints/flutter.yaml

plugins:
  import_rules: ^0.0.8

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - always_declare_return_types
    - prefer_final_locals
    - unawaited_futures
